.TH conntest 1 2013/01/05 conntest
.SH NAME
conntest \- Connection Test Utility
.SH SYNOPSIS
Client mode:
.B conntest
[ \c
.B CLIENT-OPTIONS \c
.B COMMON-OPTIONS \c
]
.PP
Server mode:
.B conntest
[ \c
.B \-S \c
.B MODE \c
.B SERVER-OPTIONS \c
.B COMMON-OPTIONS \c
]
.SH DESCRIPTION
.PP

.SH BUGS
Please report bugs you find.

.SH AUTHOR
Pekka Riikonen (priikone@iki.fi)

